# Generated by Django 5.1.4 on 2025-10-09 07:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingest', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart_type', models.CharField(choices=[('taam_radar', 'TAAM Radar'), ('bar', 'Bar Chart'), ('line', 'Line Chart'), ('pie', 'Pie Chart'), ('scatter', 'Scatter Plot'), ('heatmap', 'Heatmap')], help_text='Type of chart', max_length=20)),
                ('chart_config', models.JSONField(default=dict, help_text='Chart configuration (axes, series, labels, colors, etc.)')),
                ('is_canonical', models.BooleanField(default=False, help_text='For TAAM: whether this is the canonical persona radar')),
                ('derived_metrics', models.JSONField(default=dict, help_text='Derived metrics (distributions, heatmaps, overlay vectors, etc.)')),
                ('dataset', models.ForeignKey(help_text='Dataset this chart is based on', on_delete=django.db.models.deletion.CASCADE, related_name='chart_specs', to='ingest.uploadeddataset')),
                ('owner', models.ForeignKey(help_text='User who owns this chart', on_delete=django.db.models.deletion.CASCADE, related_name='chart_specs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chart Specification',
                'verbose_name_plural': 'Chart Specifications',
                'db_table': 'chart_specs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, help_text='Optional note about the selection')),
                ('dataset', models.ForeignKey(help_text='Dataset for this selection', on_delete=django.db.models.deletion.CASCADE, related_name='user_selections', to='ingest.uploadeddataset')),
                ('selected_chart', models.ForeignKey(help_text='The selected chart', on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='charts.chartspec')),
                ('user', models.ForeignKey(help_text='User who made the selection', on_delete=django.db.models.deletion.CASCADE, related_name='chart_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Selection',
                'verbose_name_plural': 'User Selections',
                'db_table': 'user_selections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chartspec',
            index=models.Index(fields=['owner', '-created_at'], name='chart_specs_owner_i_0f013b_idx'),
        ),
        migrations.AddIndex(
            model_name='chartspec',
            index=models.Index(fields=['dataset'], name='chart_specs_dataset_fbe7be_idx'),
        ),
        migrations.AddIndex(
            model_name='chartspec',
            index=models.Index(fields=['chart_type'], name='chart_specs_chart_t_c3a130_idx'),
        ),
        migrations.AddIndex(
            model_name='userselection',
            index=models.Index(fields=['user', 'dataset'], name='user_select_user_id_093203_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userselection',
            unique_together={('user', 'dataset')},
        ),
    ]
