# Generated by Django 5.1.4 on 2025-10-09 07:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('mime_type', models.CharField(help_text='MIME type of the uploaded file', max_length=100)),
                ('size_bytes', models.BigIntegerField(help_text='File size in bytes')),
                ('storage_path', models.CharField(help_text='Path where the file is stored', max_length=500)),
                ('original_headers', models.JSONField(default=list, help_text='Original column headers from the file')),
                ('row_count', models.IntegerField(default=0, help_text='Number of data rows (excluding header)')),
                ('parsed_ok', models.BooleanField(default=False, help_text='Whether the file was successfully parsed')),
                ('error_message', models.TextField(blank=True, help_text='Error message if parsing failed', null=True)),
                ('owner', models.ForeignKey(help_text='User who uploaded this dataset', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded Dataset',
                'verbose_name_plural': 'Uploaded Datasets',
                'db_table': 'uploaded_datasets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('row_index', models.IntegerField(help_text='Row number in the original file (0-indexed)')),
                ('data', models.JSONField(help_text='JSON representation of the row data')),
                ('dataset', models.ForeignKey(help_text='Dataset this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='parsed_records', to='ingest.uploadeddataset')),
            ],
            options={
                'verbose_name': 'Parsed Record',
                'verbose_name_plural': 'Parsed Records',
                'db_table': 'parsed_records',
                'ordering': ['dataset', 'row_index'],
            },
        ),
        migrations.AddIndex(
            model_name='uploadeddataset',
            index=models.Index(fields=['owner', '-created_at'], name='uploaded_da_owner_i_54187f_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadeddataset',
            index=models.Index(fields=['parsed_ok'], name='uploaded_da_parsed__f59a00_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedrecord',
            index=models.Index(fields=['dataset', 'row_index'], name='parsed_reco_dataset_15b0c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parsedrecord',
            unique_together={('dataset', 'row_index')},
        ),
    ]
